[always_on]
ubuntu-endpoint ansible_host=10.10.30.21
wazuh-siem ansible_host=10.10.20.10

[mode_a]
win-server-adds ansible_host=10.10.30.10
win11-endpoint ansible_host=10.10.30.20

[mode_b]
kali-attacker ansible_host=10.10.40.10
network-sensor ansible_host=10.10.30.5

[mode_c]
soc-tools ansible_host=10.10.20.11
